application: rps-bot
version: 1
runtime: go
api_version: go1.9

#automatic_scaling:
#  max_concurrent_requests: 80
#  max_idle_instances: 0

threadsafe: yes

handlers:

- url: /test\d$|/bot/(tg|viber|fbm|skype|kik|line|wechat)/.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301
