package rpstrans

const (
	GameCardTitle = "GameCardTitle"
	NewGameInlineTitle = "NewGameInlineTitle"
	NewGameInlineDescription = "NewGameInlineDescription"
	NewGameText = "NewGameText"
	AskToMakeMove = "AskToMakeMove"
	AskToMakeNextMove = "AskToMakeNextMove"
	FirstMoveDoneAwaitingSecond = "FirstMoveDoneAwaitingSecond"

	ChallengeFriendCommandText = "ChallengeFriendCommandText"

	Option1text = "Option1text"
	Option2text = "Option2text"
	Option3text = "Option3text"

	Option1emoji = "Option1emoji"
	Option2emoji = "Option2emoji"
	Option3emoji = "Option3emoji"

	Option1code = "Option1code"
	Option2code = "Option2code"
	Option3code = "Option3code"

	MT_WELCOME                      = "MT_WELCOME"
	MT_HOW_TO_START_NEW_GAME        = "MT_HOW_TO_START_NEW_GAME"
	MT_GAME_NAME                    = "MT_GAME_NAME"
	MT_NEW_GAME_WELCOME             = "MT_NEW_GAME_WELCOME"
	MT_HOW_TO_INLINE                = "MT_HOW_TO_INLINE"
	MT_RULES                        = "MT_RULES"
	MT_USER_WON_GAME                = "MT_USER_WON_GAME"
	MT_TOURNAMENT_201710_SHORT      = "MT_TOURNAMENT_201710_SHORT"
	MT_TOURNAMENT_201710_LEARN_MORE = "MT_TOURNAMENT_201710_LEARN_MORE"
	MT_TOURNAMENT_201710_PRIZES     = "MT_TOURNAMENT_201710_PRIZES"
	MT_TOURNAMENT_201710_SPONSOR    = "MT_TOURNAMENT_201710_SPONSOR"
	MT_ENROLLED_TO_TOURNAMENT       = "MT_ENROLLED_TO_TOURNAMENT"
	MT_START_SELECT_LANG            = "MT_START_SELECT_LANG"
	MT_BID_BY                       = "MT_BID_BY"
	MT_BID_TOO_BIG                  = "MT_BID_TOO_BIG"
	MT_PLAYER                       = "MT_PLAYER"
	MT_AWAITING_PLAYER              = "MT_AWAITING_PLAYER"
	MT_PLAYER_BALANCE               = "MT_PLAYER_BALANCE"
	MT_YOUR_BID                     = "MT_YOUR_BID"
	MT_CELL_OCCUPIED                = "MT_CELL_OCCUPIED"
	MT_RIVAL_HAS_TARGET_AND_BID     = "MT_RIVAL_HAS_TAARGET_AND_BID"
	MT_RIVAL_HAS_TARGET             = "MT_RIVAL_HAS_TARGET"
	MT_RIVAL_HAS_BID                = "MT_RIVAL_HAS_BID"
	MT_PLEASE_CHOOSE_YOUR_TARGET    = "MT_PLEASE_CHOOSE_YOUR_TARGET"
	MT_PLEASE_MAKE_A_BID            = "MT_PLEASE_MAKE_A_BID"
	MT_AWAITING_RIVAL_TURN          = "MT_AWAITING_RIVAL_TURN"
	MT_ASK_BID                      = "MT_ASK_BID"
	MT_LAST_BID                     = "MT_LAST_BID"
	MT_PREVIOUS_BID                 = "MT_PREVIOUS_BID"
	MT_TG_BUG_WARNING               = "MT_TG_BUG_WARNING"
	MT_NOT_A_NUMBER                 = "MT_NOT_A_NUMBER"
	MT_FREE_GAME_SPONSORED_BY       = "MT_FREE_GAME_SPONSORED_BY"
	MT_BID_IS_GREATER_THEN_BALANCE  = "MT_BID_IS_GREATER_THEN_BALANCE"
	MT_ASK_TO_RATE                  = "MT_ASK_TO_RATE"
	OUR_TWITTER                     = "OUR_TWITTER"
	OUR_FB_PAGE                     = "OUR_FB_PAGE"
	OUR_WEBSITE                     = "OUR_WEBSITE"
	INLINE_BID_TITLE                = "INLINE_BID_TITLE"
	INLINE_BID_DESC                 = "INLINE_BID_DESC"
)

const (
	C_NEW_GAME_THIS_CHAT  = "C_NEW_GAME_THIS_CHAT"
	C_NEW_GAME_WITH       = "C_NEW_GAME_WITH"
	C_NEW_GAME_OTHER_CHAT = "C_NEW_GAME_OTHER_CHAT"
	C_NEW_GAME            = "C_NEW_GAME"
)
